apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: 10Gi
  externalAccess:
    type: route
    route:
      domain: apps.ocp.tangram-soft.com
      prefix: cc-demo
  podTemplate:
    podSecurityContext:
      podSecurityContext: {}
  configOverrides:
    server:
      - confluent.controlcenter.command.topic.replication=1
      - confluent.controlcenter.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.metrics.topic.replication=1
      - confluent.monitoring.interceptor.topic.replication=1
      - confluent.controlcenter.internal.topics.replication=1
      - confluent.controlcenter.internal.topics.retention.ms=86400000
      - confluent.metrics.topic.retention.ms=86400000
      - confluent.monitoring.interceptor.topic.retention.ms=86400000
      - confluent.controlcenter.command.topic.retention.ms=86400000
      - confluent.controlcenter.ui.autoupdate.enable=false
